package render

import (
	"bytes"
	"fmt"
	"go/types"
	"strings"
	"text/template"

	"github.com/OffchainLabs/methodical-ssz/sszgen/core"
	gentypes "github.com/OffchainLabs/methodical-ssz/sszgen/types"
)

// This file is the complete HashTreeRoot operation: how every SSZ kind appends
// its contribution to the hasher, in one place.

const htrChunkSize = 32

// HashTreeRootMethodSet exposes this operation to the render orchestration.
func HashTreeRootMethodSet() core.MethodSet {
	return core.MethodSet{Name: "htr", Generate: generateHTR}
}

var htrTmpl = template.Must(template.New("htr").Parse(
	`func ({{.Receiver}} {{.Type}}) HashTreeRoot() ([32]byte, error) {
	hh := ssz.DefaultHasherPool.Get()
	if err := {{.Receiver}}.HashTreeRootWith(hh); err != nil {
		ssz.DefaultHasherPool.Put(hh)
		return [32]byte{}, err
	}
	root, err := hh.HashRoot()
	ssz.DefaultHasherPool.Put(hh)
	return root, err
}
{{.MixinDeclaration}}
func ({{.Receiver}} {{.Type}}) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()
	{{.HTRSteps}}
	{{.MerkleizeCall}}
	return nil
}`))

func generateHTR(vc *gentypes.ValueContainer, ctx *core.GenContext) ([]string, error) {
	if vc.ActiveFields != nil {
		// progressive containers expose their progressive root through the
		// standard method names; the bodies are generated by the
		// htr-progressive method set
		return []string{execTmpl(htrProgressiveWrapperTmpl, fieldElements{FieldName: "*" + vc.TypeName()})}, nil
	}
	steps := make([]string, 0)
	for i, c := range vc.Contents {
		ref := fmt.Sprintf("%s.%s", htrReceiver, c.Key)
		steps = append(steps, fmt.Sprintf("\t// Field %d: %s", i, c.Key))
		steps = append(steps, core.Dispatch(htrOp{field: c.Key}, c.Value, ref, ctx))
	}
	buf := bytes.NewBuffer(nil)
	err := htrTmpl.Execute(buf, struct {
		Receiver         string
		Type             string
		HTRSteps         string
		MixinDeclaration string
		MerkleizeCall    string
	}{
		Receiver:         htrReceiver,
		Type:             "*" + vc.TypeName(),
		HTRSteps:         strings.Join(steps, "\n"),
		MixinDeclaration: "",
		MerkleizeCall:    "hh.Merkleize(indx)",
	})
	if err != nil {
		return nil, err
	}
	return []string{buf.String()}, nil
}

const htrReceiver = "c"

// htrProgressiveWrapperTmpl: the standard hashing methods of a progressive
// container delegate to its progressive forms, so callers and generated
// parents use HashTreeRoot[With] uniformly. FieldName carries the receiver
// type.
var htrProgressiveWrapperTmpl = template.Must(template.New("htrProgressiveWrapper").Parse(
	`func (c {{.FieldName}}) HashTreeRoot() ([32]byte, error) {
	return c.ProgressiveHashTreeRoot()
}

func (c {{.FieldName}}) HashTreeRootWith(hh *ssz.Hasher) error {
	return c.ProgressiveHashTreeRootWith(hh)
}`))

// htrOp is the per-kind visitor for the HashTreeRoot operation. field carries the
// clean name of the enclosing struct field (no receiver prefix), threaded down
// through pointers, overlays, and collection elements so a nested
// HashTreeRoot[With] failure can wrap its error with the field where it occurred.
type htrOp struct{ field string }

func (htrOp) Name() string                                    { return "htr" }
func (htrOp) Delegates(ctx *core.GenContext) *types.Interface { return ctx.Ifaces().LightHasher }

// Delegate: the field type already implements the hasher interface; call it.
// A full hasher contributes directly; a light (HashTreeRoot-only) one is appended.
func (o htrOp) Delegate(vr gentypes.ValRep, ref string, ctx *core.GenContext) string {
	if vr.SatisfiesInterface(ctx.Ifaces().FullHasher) {
		return execTmpl(htrCallTmpl, htrCallElements{FieldName: ref, Field: o.field})
	}
	return execTmpl(htrLightCallTmpl, htrCallElements{FieldName: ref, Field: o.field})
}

func (htrOp) Bool(_ *gentypes.ValueBool, ref string, _ *core.GenContext) string {
	return fmt.Sprintf("hh.PutBool(%s)", ref)
}
func (htrOp) Byte(_ *gentypes.ValueByte, ref string, _ *core.GenContext) string {
	return fmt.Sprintf("hh.PutUint8(%s)", ref)
}
func (htrOp) Union(*gentypes.ValueUnion, string, *core.GenContext) string {
	panic("union types are not supported")
}
func (htrOp) Uint(v *gentypes.ValueUint, ref string, _ *core.GenContext) string {
	if v.Size > 64 {
		return htrWideUint(ref, v.Size)
	}
	return fmt.Sprintf("hh.PutUint%d(%s)", v.Size, ref)
}

// htrWideUint emits unrolled little-endian limb appends for a uint wider than
// 64 bits: for uint256 the four limbs are exactly one chunk. (A uint128 would
// need a trailing FillUpTo32 in scalar position, but no Go representation
// produces one today.)
func htrWideUint(ref string, size gentypes.UintSize) string {
	lines := make([]string, int(size)/64)
	for i := range lines {
		lines[i] = fmt.Sprintf("hh.AppendUint64(%s[%d])", ref, i)
	}
	return strings.Join(lines, "\n")
}

func (o htrOp) Container(_ *gentypes.ValueContainer, ref string, _ *core.GenContext) string {
	return execTmpl(htrCallTmpl, htrCallElements{FieldName: ref, Field: o.field})
}

func (o htrOp) Pointer(v *gentypes.ValuePointer, ref string, ctx *core.GenContext) string {
	return core.Dispatch(htrOp{field: o.field}, v.Referent, ref, ctx)
}

func (o htrOp) Overlay(v *gentypes.ValueOverlay, ref string, ctx *core.GenContext) string {
	if v.IsBitfield() {
		if ul, ok := v.Underlying.(*gentypes.ValueList); ok && ul.Progressive {
			return execTmpl(htrProgressiveBitlistTmpl, fieldElements{FieldName: ref})
		}
	}
	if v.IsBitfield() && v.Name == "Bitlist" {
		ul, ok := v.Underlying.(*gentypes.ValueList)
		if !ok {
			panic(fmt.Sprintf("unexpected underlying type for Bitlist, expected ValueList, got %v", v.Underlying))
		}
		return execTmpl(htrBitlistTmpl, bitlistPutElements{FieldName: ref, MaxSize: ul.MaxSize})
	}
	return core.Dispatch(htrOp{field: o.field}, v.Underlying, core.Coerce(v.Underlying)(ref), ctx)
}

func (o htrOp) Vector(v *gentypes.ValueVector, ref string, ctx *core.GenContext) string {
	nested, coerce, vr := resolveElement(ref, v.ElementValue)
	vpe := vecPutterElements{FieldName: ref, NestedFieldName: nested, Size: v.Size}
	if bl := bitlistElement(v.ElementValue); bl != nil {
		// each element's PutBitlist collapses to its own root chunk (mixin
		// included), so the elements compose under a plain merkleize
		vpe.AppendCall = core.Dispatch(htrOp{field: o.field}, bl, nested, ctx)
		vpe.Merkleize = "hh.Merkleize(subIndx)"
		return execTmpl(generateVectorHTRPutterTmpl, vpe)
	}
	switch ev := vr.(type) {
	case *gentypes.ValueByte:
		suffix := ""
		if v.IsArray {
			suffix = "[:]"
		}
		return execTmpl(bytePutBytesTmpl, byteVectorElements{FieldName: ref, Size: v.Size, Suffix: suffix})
	case *gentypes.ValueVector:
		if isByteVector(ev) {
			vpe.AppendCall = renderByteSliceAppend(ev, nested)
		} else {
			// vector of non-byte vectors: each element collapses to its own root
			vpe.AppendCall = core.Dispatch(htrOp{field: o.field}, ev, nested, ctx)
		}
		vpe.Merkleize = "hh.Merkleize(subIndx)"
		return execTmpl(generateVectorHTRPutterTmpl, vpe)
	case *gentypes.ValueContainer:
		vpe.AppendCall = core.Dispatch(htrOp{field: o.field}, ev, nested, ctx)
		vpe.Merkleize = "hh.Merkleize(subIndx)"
		return execTmpl(generateVectorHTRPutterTmpl, vpe)
	case *gentypes.ValueList:
		// Vector of lists: each element collapses to its own root (with length
		// mixin), and the element roots merkleize with no mixin — a vector's
		// length is part of the type.
		vpe.AppendCall = core.Dispatch(htrOp{field: o.field}, ev, nested, ctx)
		vpe.Merkleize = "hh.Merkleize(subIndx)"
		return execTmpl(generateVectorHTRPutterTmpl, vpe)
	case *gentypes.ValueUint:
		if ev.Size > 64 {
			vpe.AppendCall = htrWideUint(nested, ev.Size)
		} else {
			vpe.AppendCall = fmt.Sprintf("hh.AppendUint%d(%s)", ev.Size, coerce(nested))
		}
		vpe.Merkleize = "hh.Merkleize(subIndx)"
		return execTmpl(generateVectorHTRPutterTmpl, vpe)
	case *gentypes.ValueBool:
		// bools pack one byte per element; merkleizeInput zero-pads the
		// trailing partial chunk
		vpe.AppendCall = fmt.Sprintf("hh.AppendBool(%s)", coerce(nested))
		vpe.Merkleize = "hh.Merkleize(subIndx)"
		return execTmpl(generateVectorHTRPutterTmpl, vpe)
	default:
		panic(fmt.Sprintf("unsupported type combination - %v vector of %v", ref, ev))
	}
}

func (o htrOp) List(v *gentypes.ValueList, ref string, ctx *core.GenContext) string {
	nested, coerce, vr := resolveElement(ref, v.ElementValue)
	if v.Progressive {
		return progressiveListPutter(v, ref, nested, coerce, vr, ctx, o.field)
	}
	lpe := listPutterElements{FieldName: ref, NestedFieldName: nested, MaxSize: v.MaxSize}
	if bl := bitlistElement(v.ElementValue); bl != nil {
		// each element's PutBitlist collapses to its own root chunk (mixin
		// included), so the elements compose under the outer length mixin
		lpe.AppendCall = core.Dispatch(htrOp{field: o.field}, bl, nested, ctx)
		lpe.Merkleize = fmt.Sprintf("hh.MerkleizeWithMixin(subIndx, uint64(len(%s)), %d)", ref, v.MaxSize)
		return execTmpl(generateListHTRPutterTmpl, lpe)
	}
	switch ev := vr.(type) {
	case *gentypes.ValueByte:
		return execTmpl(listByteHTRPutterTmpl, listLimitElements{
			FieldName:   ref,
			MaxSize:     v.MaxSize,
			ElementSize: ev.FixedSize(),
		})
	case *gentypes.ValueVector:
		if isByteVector(ev) {
			lpe.AppendCall = renderByteSliceAppend(ev, nested)
		} else {
			// list of non-byte vectors: each element collapses to its own root
			lpe.AppendCall = core.Dispatch(htrOp{field: o.field}, ev, nested, ctx)
		}
		lpe.Merkleize = fmt.Sprintf("hh.MerkleizeWithMixin(subIndx, uint64(len(%s)), %d)", ref, v.MaxSize)
		return execTmpl(generateListHTRPutterTmpl, lpe)
	case *gentypes.ValueUint:
		if ev.Size > 64 {
			lpe.AppendCall = htrWideUint(nested, ev.Size)
		} else {
			lpe.AppendCall = fmt.Sprintf("hh.AppendUint%d(%s)", ev.Size, coerce(nested))
		}
		if ev.FixedSize()%htrChunkSize != 0 {
			lpe.PadCall = "\nhh.FillUpTo32()"
		}
		lpe.Merkleize = execTmpl(merkleizeCalculateLimitTmpl, listLimitElements{
			FieldName:   ref,
			MaxSize:     v.MaxSize,
			ElementSize: ev.FixedSize(),
		})
		return execTmpl(generateListHTRPutterTmpl, lpe)
	case *gentypes.ValueContainer:
		lpe.AppendCall = core.Dispatch(htrOp{field: o.field}, ev, nested, ctx)
		lpe.Merkleize = fmt.Sprintf("hh.MerkleizeWithMixin(subIndx, uint64(len(%s)), %d)", ref, v.MaxSize)
		return execTmpl(generateListHTRPutterTmpl, lpe)
	case *gentypes.ValueList:
		lpe.AppendCall = core.Dispatch(htrOp{field: o.field}, ev, nested, ctx)
		lpe.Merkleize = fmt.Sprintf("hh.MerkleizeWithMixin(subIndx, uint64(len(%s)), %d)", ref, v.MaxSize)
		return execTmpl(generateListHTRPutterTmpl, lpe)
	case *gentypes.ValueBool:
		lpe.AppendCall = fmt.Sprintf("hh.AppendBool(%s)", coerce(nested))
		if ev.FixedSize()%htrChunkSize != 0 {
			lpe.PadCall = "\nhh.FillUpTo32()"
		}
		lpe.Merkleize = execTmpl(merkleizeCalculateLimitTmpl, listLimitElements{
			FieldName:   ref,
			MaxSize:     v.MaxSize,
			ElementSize: ev.FixedSize(),
		})
		return execTmpl(generateListHTRPutterTmpl, lpe)
	default:
		panic(fmt.Sprintf("unsupported type combination - list of %v", ev))
	}
}

// bitlistElement returns the bitlist overlay of a vector/list element (after
// unwrapping any pointer levels), or nil. Bitlist elements get a dedicated
// branch in the collection putters: resolveElement's overlay-stripping would
// otherwise hash them as plain byte lists, losing each element's length mixin.
func bitlistElement(elem gentypes.ValRep) *gentypes.ValueOverlay {
	for {
		ptr, ok := elem.(*gentypes.ValuePointer)
		if !ok {
			break
		}
		elem = ptr.Referent
	}
	ov, ok := elem.(*gentypes.ValueOverlay)
	if !ok || !ov.IsBitfield() {
		return nil
	}
	if _, isList := ov.Underlying.(*gentypes.ValueList); !isList {
		return nil
	}
	return ov
}

// resolveElement strips a pointer and an overlay off a vector/list element type,
// returning the nested loop-variable name, an element-coerce rewriter (identity
// unless the element was an overlay), and the resolved underlying type.
func resolveElement(fieldName string, elem gentypes.ValRep) (nested string, coerce core.Rewriter, vr gentypes.ValRep) {
	nested = "o"
	if fieldName[0:1] == "o" && monoCharacter(fieldName) {
		nested = fieldName + "o"
	}
	coerce = func(s string) string { return s }
	vr = elem
	if ptr, ok := vr.(*gentypes.ValuePointer); ok {
		vr = ptr.Referent
	}
	if ov, ok := vr.(*gentypes.ValueOverlay); ok {
		uTn := ov.Underlying.TypeName()
		coerce = func(s string) string { return fmt.Sprintf("%s(%s)", uTn, s) }
		vr = ov.Underlying
	}
	return nested, coerce, vr
}

func monoCharacter(s string) bool {
	ch := s[0]
	for i := 1; i < len(s); i++ {
		if s[i] != ch {
			return false
		}
	}
	return true
}

func isByteVector(v *gentypes.ValueVector) bool {
	_, isByte := v.ElementValue.(*gentypes.ValueByte)
	return isByte
}

// renderByteSliceAppend: a 32-byte vector is one chunk (Append it directly);
// other sizes must be merkleized (PutBytes).
func renderByteSliceAppend(v *gentypes.ValueVector, fieldName string) string {
	suffix := ""
	if v.IsArray {
		suffix = "[:]"
	}
	t := bytePutBytesTmpl
	if v.Size == htrChunkSize {
		t = byteAppendTmpl
	}
	return execTmpl(t, byteVectorElements{FieldName: fieldName, Size: v.Size, Suffix: suffix})
}

// byteVectorElements parameterizes the byte-vector hash snippets: the field, its
// expected length, and a "[:]" suffix when the field is an array (not a slice).
type byteVectorElements struct {
	FieldName string
	Size      int
	Suffix    string
}

// listLimitElements parameterizes the list hash fragments whose chunk limit is
// computed from the list's max size and element size.
type listLimitElements struct {
	FieldName   string
	MaxSize     int
	ElementSize int
}

// bitlistPutElements parameterizes the bitlist hash block.
type bitlistPutElements struct {
	FieldName string
	MaxSize   int
}

// htrCallElements parameterizes the nested HashTreeRoot[With] call: the field
// reference to hash and the clean field name its error is wrapped with.
type htrCallElements struct {
	FieldName string
	Field     string
}

var (
	htrCallTmpl = template.Must(template.New("htrCall").Parse(
		`if err := {{.FieldName}}.HashTreeRootWith(hh); err != nil {
	return fmt.Errorf("{{.Field}}: %w", err)
}`))

	htrLightCallTmpl = template.Must(template.New("htrLightCall").Parse(
		`if hash, err := {{.FieldName}}.HashTreeRoot(); err != nil {
	return fmt.Errorf("{{.Field}}: %w", err)
} else {
	hh.AppendBytes32(hash[:])
}`))

	htrBitlistTmpl = template.Must(template.New("htrBitlist").Parse(
		`if len({{.FieldName}}) == 0 {
	return ssz.ErrEmptyBitlist
}
hh.PutBitlist({{.FieldName}}, {{.MaxSize}})`))

	htrProgressiveBitlistTmpl = template.Must(template.New("htrProgressiveBitlist").Parse(
		`if len({{.FieldName}}) == 0 {
	return ssz.ErrEmptyBitlist
}
hh.PutProgressiveBitlist({{.FieldName}})`))

	byteAppendTmpl = template.Must(template.New("byteAppend").Parse(
		`if len({{.FieldName}}) != {{.Size}} {
	return ssz.ErrBytesLength
}
hh.Append({{.FieldName}}{{.Suffix}})`))

	bytePutBytesTmpl = template.Must(template.New("bytePutBytes").Parse(
		`if len({{.FieldName}}) != {{.Size}} {
	return ssz.ErrBytesLength
}
hh.PutBytes({{.FieldName}}{{.Suffix}})`))

	merkleizeCalculateLimitTmpl = template.Must(template.New("merkleizeCalculateLimit").Parse(
		`numItems := uint64(len({{.FieldName}}))
hh.MerkleizeWithMixin(subIndx, numItems, ssz.CalculateLimit({{.MaxSize}}, numItems, {{.ElementSize}}))`))

	listByteHTRPutterTmpl = template.Must(template.New("listByteHTRPutter").Parse(`
{
	if len({{.FieldName}}) > {{.MaxSize}} {
		return ssz.ErrBytesLength
	}
	subIndx := hh.Index()
	hh.AppendBytes32({{.FieldName}})
	numItems := uint64(len({{.FieldName}}))
	hh.MerkleizeWithMixin(subIndx, numItems, ({{.MaxSize}}*{{.ElementSize}} + 31)/32)
}
`))

	generateVectorHTRPutterTmpl = template.Must(template.New("vectorHTRPutter").Parse(`{
	if len({{.FieldName}}) != {{.Size}} {
		return ssz.ErrVectorLength
	}
	subIndx := hh.Index()
	for _, {{.NestedFieldName}} := range {{.FieldName}} {
		{{.AppendCall}}
	}
	{{.Merkleize}}
}`))

	generateListHTRPutterTmpl = template.Must(template.New("listHTRPutter").Parse(`{
	if len({{.FieldName}}) > {{.MaxSize}} {
		return ssz.ErrListTooBig
	}
	subIndx := hh.Index()
	for _, {{.NestedFieldName}} := range {{.FieldName}} {
		{{.AppendCall}}
	}
	{{- .PadCall}}
	{{.Merkleize}}
}`))
)

type vecPutterElements struct {
	FieldName       string
	NestedFieldName string
	Size            int
	AppendCall      string
	Merkleize       string
}

type listPutterElements struct {
	FieldName       string
	NestedFieldName string
	MaxSize         int
	AppendCall      string
	PadCall         string
	Merkleize       string
}
